### ISSUE TITLE
tinfl.c uses mz_uint64 even if MINIZ_HAS_64BIT_REGISTERS is 0

### ISSUE THREAD

**Issue by igy137** [richgel999/miniz#100]
tinfl.c:571 & 603 uses mz_uint64 

bit_buf &= (tinfl_bit_buf_t)((((mz_uint64)1) << num_bits) - (mz_uint64)1);

even if MINIZ_HAS_64BIT_REGISTERS  is not set.
In this case tinfl_bit_buf_t is defined as mz_uint32. 
I guess num_bits should not go above 32, so mz_uint32 could be used for the above op.

**Comment by uroni** [comment]
It uses that define only as a switch for performance (cpu has 64bit registers, so 64bit operations are fast).
See the comment:
/* Set MINIZ_HAS_64BIT_REGISTERS to 1 if operations on 64-bit integers are reasonably fast (and don't involve compiler generated calls to helper functions). */
