### ISSUE TITLE
warnings and static analysis

### ISSUE THREAD

**Issue by minad** [richgel999/miniz#110]
I am using miniz vendored in a project. I am using strict warning settings in clang and gcc. I am getting warnings due to miniz "conversion", "sign-conversion", "cast-qual", "cast-align", "unused-parameter", "switch-enum", "c++-compat". It would be nice if some of those could be fixed in miniz. Would you accept patches?

Furthermore by using clang static analyis via the "scan-build" tool a few more issues are uncovered. Unused assignments etc.

**Comment by minad** [comment]
@richgel999 Since there are already other open issues concerning warnings, do you need those PRs to be split somehow per warning or rebased on master?

See #101, #91 and #102.

**Comment by uroni** [comment]
Preferably pull requests on master split by warning type (easier to review).

**Comment by minad** [comment]
@uroni I fixed a few easy ones here to get started https://github.com/richgel999/miniz/pull/111

-Wconversion etc require more changes, I will create separate PRs.

**Comment by minad** [comment]
cast-qual: #112
