### ISSUE TITLE
Enum values related question

### ISSUE THREAD

**Issue by shahzeb1** [richgel999/miniz#115]
https://github.com/richgel999/miniz/blob/f3461d636a7e02fae7858b60cbcc006bf9f29766/miniz.h#L209-L216

Just curious but don't C enums by default take in numerical values from 0 incrementing up. Isn't assigning numbers to them redundant code?

**Comment by paulharris** [comment]
Yes, but, I sometimes do this myself to be exact about what keyword means what number exactly.
Better to overspecify than to leave something implicit.

Plus there are added bonuses, for example,
if you see a variable assigned to 4 in a debugger, you can grep source code files for "4".
Nice to find all the magic codes that mean "4".
Can't do that if the numbers weren't written down in the sourcecode.

**Comment by shahzeb1** [comment]
Thanks for the clarification.
