### ISSUE TITLE
Problem on macOS for file name that contains forward slash

### ISSUE THREAD

**Issue by omergoktas** [richgel999/miniz#118]
On macOS it is valid to have a file or folder name that contains '/' character (in user space). Those '/' characters are automatically converted to ':' characters (in programming space) . So for instance, if you have a file called "hello/world.txt" on your Desktop, you get "hello:world.txt" in C/C++. That (':') causes a MZ_ZIP_INVALID_FILENAME error for such files on macOS. 

Problematic line in the code:

https://github.com/richgel999/miniz/blob/f3461d636a7e02fae7858b60cbcc006bf9f29766/miniz_zip.c#L3106

**Comment by uroni** [comment]
It is probably a try to implement this from the "specification":

> 4.4.17 file name: (Variable)
> 
>        4.4.17.1 The name of the file, with optional relative path.
>        The path stored MUST NOT contain a drive or
>        device letter, or a leading slash.  All slashes
>        MUST be forward slashes '/' as opposed to
>        backwards slashes '\' for compatibility with Amiga
>        and UNIX file systems etc.  If input came from standard
>        input, there is no file name field. 

On Linux a file name can contain everything except for \0 or /. On MacOS it's probably about the same, and Windows has a myriad of restrictions.
I think it might be better to give responsibility of using sensible (portable) file names to the program using miniz and just check for the forward slash in this function.

**Comment by uroni** [comment]
25de35faec2430c4cd2be9f8294ac319b5cbe602

**Comment by omergoktas** [comment]
I think that's fine, thanks
