### ISSUE TITLE
Infinite Loop in miniz_tester.cpp:652

### ISSUE THREAD

**Issue by ChijinZ** [richgel999/miniz#123]
When testcase(https://github.com/ChijinZ/security_advisories/blob/master/miniz-2.0.8/infinite_loop) is input into miniz_tester(command: ./miniz_tester -v -b -r d testcase output), program fell into infinite loop and produce an infinite large output until disk space become insufficient. It may cause series of problems, please check it out.

**Comment by uroni** [comment]
If you are expecting potentially hostile zip/compressed input you should use one of the functions that extract to callbacks, then fail the callback once you have more than the expected maximum amount of uncompressed data. What the maximum size the compressed data can explode to actually is depends on the use case. For images, for example, it is probably something like the max number of pixels times a constant factor.
