### ISSUE TITLE
How can I use multiple threads to accelerate the decompression?

### ISSUE THREAD

**Issue by lee-bin** [richgel999/miniz#130]
Is there any way to achieve that?

**Comment by lee-bin** [comment]
Can I split a file to 4 parts and zip them to one `filename.zip`, then use `mz_zip_reader_extract_file_to_mem` in 4 threads to extract it?
Is `mz_zip_reader_extract_file_to_mem` thread safe?

**Comment by uroni** [comment]
The default function for reading from the ZIP file does a seek+then read (mz_file_read_func_stdio), so not thread safe. You could open the zip file multiple times.

**Comment by lee-bin** [comment]
Thanks for your advice. I read all the data to buffer and then use `mz_zip_reader_extract_to_mem` to unzip. It's maybe slower than your method.
