### ISSUE TITLE
PATCH: mz_zip_reader_init_file_stream

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richgel999/miniz#17]
```
This patch adds a function to read zip files from an already-open FILE*.

We do some silly things with FILE* to work with zip files in our virtual 
filesystem, which might not be backed by an actual on-disk file. This lets us 
do that.
```

Original issue reported on code.google.com by `r...@fastmail.fm` on 28 Sep 2013 at 11:24

Attachments:
- [miniz-zip-read-stream.diff](https://storage.googleapis.com/google-code-attachments/miniz/issue-17/comment-0/miniz-zip-read-stream.diff)

**Comment by uroni** [comment]
Please reopen as pull request if this is still relevant.
