### ISSUE TITLE
CMake and pkg-config files are missing from miniz-2.2.0.zip

### ISSUE THREAD

**Issue by ppisar** [richgel999/miniz#201]
miniz-2.2.0 ChangeLog.md mentions CMake and pkg-config support, no such files are included in the release ZIP archive miniz-2.2.0.zip.

**Comment by uroni** [comment]
The other (source code) ZIP file doesn't work?

**Comment by ppisar** [comment]
V Wed, Aug 11, 2021 at 12:34:12PM -0700, Martin Raiber napsal(a):
> The other (source code) ZIP file doesn't work?
> 
The other 2.2.0.zip and 2.2.0.tar.gz work. Probably because they are git
snapshots while miniz-2.2.0.zip is a release archive.
