### ISSUE TITLE
Using MZ_DEFAULT_COMPRESSION creates broken archives

### ISSUE THREAD

**Issue by Amomum** [richgel999/miniz#210]
Comment states that `MZ_DEFAULT_COMPRESSION=MZ_DEFAULT_LEVEL`:
https://github.com/richgel999/miniz/blob/e6a7c5daeddf59ecc957049e8e97edac7d4922da/miniz.h#L252

But that is not strictly true:
https://github.com/richgel999/miniz/blob/e6a7c5daeddf59ecc957049e8e97edac7d4922da/miniz.h#L259-L260

Because of this `mz_zip_writer_add_file` treats them a bit differently:
https://github.com/richgel999/miniz/blob/e6a7c5daeddf59ecc957049e8e97edac7d4922da/miniz_zip.c#L3481-L3486

So if I use `MZ_DEFAULT_COMPRESSION`, `MZ_ZIP_GENERAL_PURPOSE_BIT_FLAG_UTF8` will not be set in `gen_flags` and resulting zip-file will be broken (it will contain files of size 0), with no apparent error generated, all functions will return MZ_TRUE.

`mz_zip_validate_archive`, however, will not validate such archive (as expected).

I'm not exactly sure why this happens, maybe it only affects my Windows 10 machine but still, I don't see any reason why `MZ_DEFAULT_COMPRESSION` can't just be equal to `MZ_DEFAULT_LEVEL` to avoid this issue altogether.

<details> <summary>Example code</summary>

``` c
    mz_zip_archive zip_archive;
    memset(&zip_archive, 0, sizeof(zip_archive));

    bool res = false;

    const char * archive_path = ...;

    res = mz_zip_writer_init_file(&zip_archive, archive_path, 0); 
    assert(res);

    const char * file_path = ...;

    res = mz_zip_writer_add_file(&zip_archive, "aaa.txt", file_path, nullptr, 0, MZ_DEFAULT_COMPRESSION);
    assert(res);

    res = mz_zip_writer_finalize_archive(&zip_archive);
    assert(res);

    res = mz_zip_writer_end(&zip_archive);
    assert(res);

    res = mz_zip_reader_init_file(&zip_archive, archive_path, 0);
    assert(res);

    res = mz_zip_validate_archive(&zip_archive, 0);
    assert(res);

    res = mz_zip_reader_end(&zip_archive);
    assert(res);
```

</details>

**Comment by uroni** [comment]
Thanks for reporting this issue. Should be fixed with 3e5e488ba9e86bfcbd7532f3d68b4e42bc540f00 .
