### ISSUE TITLE
unnecessary hastle to contribute

### ISSUE THREAD

**Issue by manxorist** [richgel999/miniz#211]
Contributing fixes to miniz is severely complicated by the confusing development workflow of not having the files that are actually in the release package in the repository. As a user of miniz I am requested to use the release package. Thus any fixes I create patches for in my downstream repository will not at all apply to the miniz repository.

Please reconsider either the repository contents, or the request to use the amalgamation.

**Comment by uroni** [comment]
Changed the readme (removing request to use amalgamation). This might clear things up.
