### ISSUE TITLE
various fixes

### ISSUE THREAD

**Issue by manxorist** [richgel999/miniz#212]
We have been using the following changes (or similar) since years in [libopenmpt](https://github.com/OpenMPT/openmpt), please consider fixing:
 *  Fix function definitions `tdefl_compressor_alloc(void)` and `tinfl_decompressor_alloc(void)` to not accept any amount of arguments.
 *  Avoid extending alignment requirement through pointer casts which caused `warning: cast from 'const mz_uint8 *' (aka 'const unsigned char *') to 'const mz_uint32 *' (aka 'const unsigned int *') increases required alignment from 1 to 4 [-Wcast-align]`.
 *  Avoid use of undefined `__BYTE_ORDER__` macro with MSVC.
 *  Unaligned pointer access is undefined behavior in C. `#define MINIZ_USE_UNALIGNED_LOADS_AND_STORES 1` must **never** be the default.
 *  Various functions in miniz.h should not be declared when `#define MINIZ_NO_STDIO` is used.

See <https://manx.datengang.de/openmpt/temp/miniz-libopenmpt-fixes-v1.patch>.

**Comment by uroni** [comment]
Your changes look good. Should I pick them or do you want to open a pull request?

**Comment by manxorist** [comment]
Please feel free to just pick them and maybe adjust as you see fit.

**Comment by uroni** [comment]
Done. Thanks!
