### ISSUE TITLE
example 1 not working - deflate assertion failures

### ISSUE THREAD

**Issue by jorunv** [richgel999/miniz#215]
I'm trying to run example 1 with miniz version 2.2.0 on an ESP32, building with the esp-idf tools.

The compression fails on different asserts:

assertion "d->m_huff_code_sizes[0][lit]" failed: file "../miniz_tdef.c", line 585, function: tdefl_compress_lz_codes
assertion "d->m_huff_code_sizes[0][sym]" failed: file "../miniz_tdef.c", line 578, function: tdefl_compress_lz_codes

When putting these in asserts in comment, the compression finishes, but the decompression fails because the data was not compressed correctly. 

The inflate function returns a failure (MZ_DATA_ERROR) after calling the function tinfl_decompress. This last function fails on lines 324-327 in miniz_tinfl.c

`if ((65536 != total) && (used_syms > 1))
 {
         TINFL_CR_RETURN_FOREVER(35, TINFL_STATUS_FAILED);
}`

Does anyone have an idea what might be causing this issue?

**Comment by uroni** [comment]
So I read https://esp32.com/viewtopic.php?t=1076 per chance and it says the miniz inflate/deflate is contained in ESP32 ROM. So maybe the symbol names clash with the ROM version.

If you only need tinf/tdef maybe use the ROM version?

Otherwise what miniz version is it using (``esp-idf/components/esp32/include/rom/miniz.h`)?

**Comment by jorunv** [comment]
Sorry for my delayed answer. I've changed my version to match the version contained in ESP32 ROM and used the header file in the esp-idf components instead of the header files of this library. I'm not sure if it was a clash of symbol names or just a wrong configuration for the esp32 in the standard library header files, but these changes solved the issues described above. 

Thanks for the help!

**Comment by Noushadalik** [comment]
Hi,
I'm trying to run example1 with miniz version 2.0.2 for matching my esp idf component miniz version (9.1.15) but I got compression failed how to fix it?
esp idf log :
**miniz.c version: 9.1.15
compress() failed!**
Does anyone have any idea about the proper integration of miniz to esp32? (esp idf version 4.4.1)
