### ISSUE TITLE
Unaligned memory issues

### ISSUE THREAD

**Issue by nedelec** [richgel999/miniz#230]
Hello, 
I installed MINIZ to encode image with spng, on MacOS 10.14.6 (Intel Core i7).
I got two 'Unaligned Memory Access' errors, but I was able to fix them:

Line 1116--1119

        mz_uint match_len = pLZ_codes[0];
        //mz_uint match_dist = *(const mz_uint16 *)(pLZ_codes + 1);
        mz_uint match_dist = 256 * (mz_uint)pLZ_codes[2] + (mz_uint)pLZ_codes[1];

Line 1163:

        //*(mz_uint64 *)pOutput_buf = bit_buffer;
        memcpy(pOutput_buf, &bit_buffer, 8);

 And with these modifications it works!

I get lots of warnings relating to 'comma' use, but that is another story.
You are using them correctly, but a ';' would do the same job, and not trigger so many warnings...
Thank you very much for the excellent work!
Greetings from Cambridge, UK

**Comment by biodranik** [comment]
Can you please create a pull request with your fixes?
