### ISSUE TITLE
miniz reports missing large file support on 64-bit Linux

### ISSUE THREAD

**Issue by fabiangreffrath** [richgel999/miniz#257]
Hi,

this gets reported if miniz is compiled with the default flags on a Debian amd64 system:

```make
/home/runner/work/woof/woof/miniz/miniz.c:3089:9: note: #pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.
 3089 | #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
```

Looks like the `else` path here should at least check for being compiled on a 64-bit system, or `sizeof(off_t) < 8` before emitting such a warning:

https://github.com/richgel999/miniz/blob/ca0cdfc52d193bf738e59e47c5206812a3315bcd/miniz_zip.c#L164-L165

**Comment by ell1e** [comment]
If you include `stdio.h` or some other header too early before miniz without declaring the right large file source defines, it is possible to accidentally disable 64-bit file support on a 64-bit system. I'm guessing this is what you ran into, in which case I'm not sure why there's any issue with miniz here and you probably just need to fix your project's CFLAGS (or if you don't then large file support will indeed remain disabled exactly as the warning says, and there isn't much miniz can possibly do about it).

**Comment by fabiangreffrath** [comment]
It is my understanding that you have 64-bit file support on a Linux 64-bit system *without* any additional defines. It might make more sense to check the actual `sizeof(off_t)` before issuing such a warning.

> it is possible to accidentally disable 64-bit file support on a 64-bit system

Are you sure this is really possible?

**Comment by ell1e** [comment]
> Are you sure this is really possible?

Now that you ask, no :smile:  butit certainly is possible that `stdio.h` just won't define the functions like `ftello` for you. Whether miniz would actually *need* to use those on a 64-bit system I wouldn't know, I guess maybe not. Very good question.

(In any case, using the defines I mentioned will also ensure large file support for 32-bit compilation targets, so I'd say they're still useful while not harmful for 64-bit systems.)

**Comment by fabiangreffrath** [comment]
Maybe the following check should be added to the `#else` clause preceding the `#pragma message()` call:
```
#else if !defined(_FILE_OFFSET_BITS) || (_FILE_OFFSET_BITS != 64)
```
