### ISSUE TITLE
Is it possible to get the compression level when inflating?

### ISSUE THREAD

**Issue by SoylentGraham** [richgel999/miniz#269]
I couldn't see anything around this, and I'm presuming there is no such thing (only "better" dictionaries etc), but asking just in case that information is there to be extracted

**Comment by jsummers** [comment]
If your data is in zlib or ZIP format, then a field for the reported compression level exists. But it's not very trustworthy.

For zlib, the reported compression level is in the two high bits of the second byte of the stream:
`(tinfl_decompressor::m_zhdr1 & 0xc0)>>6`,
0=fastest, 1=fast, 2=default, 3=max.

For ZIP format, assuming `mz_zip_archive_file_stat::m_method==8`, the reported compression level is in two bits of the "general purpose bit flag" field:
`(mz_zip_archive_file_stat::m_bit_flag & 0x0006)>>1`,
3=superfast, 2=fast, 0=normal, 1=max.

(I don't know how accessible these fields are in miniz.)

**Comment by SoylentGraham** [comment]
gzip is my container unfortunetly, which I'm pretty sure doesnt have it (although maybe I should re-check the comments field :)

**Comment by jsummers** [comment]
Gzip's "extra flags" field might, at best, tell you if min compression was used, or if max compression was used. That's outside the scope of miniz, as far as I know.

The Deflate format by itself has no information about the compression level.

**Comment by SoylentGraham** [comment]
nah unfortunetly not, I was hoping that maybe it was inside `deflate` rather than the containers, (so yeah, if it is in a container, out of scope for miniz :)
