### ISSUE TITLE
Remove archived file from central directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richgel999/miniz#34]
```
It would be great if the library supported file removal from the central 
directory and compress of a new file to a specific file index. This would let 
us overwrite a single file content with new data without wasting memory.
```

Original issue reported on code.google.com by `marcoalt...@gmail.com` on 6 Jun 2014 at 4:35

**Comment by Temtaime** [comment]
3 years have passed and still no function to remove the file ?

**Comment by yjygit** [comment]
5 years have passed and still no function to remove the file ?

**Comment by uroni** [comment]
Closed because not a bug (feature request)
