### ISSUE TITLE
Doesn't compile when MINIZ_NO_ARCHIVE_WRITING_APIS is defined

### ISSUE THREAD

**Issue by pragusc** [richgel999/miniz#59]
(I mean, it does compile, complaining about an implicit declaration, but it doesn't link.)

That's because function mz_zip_end uses mz_zip_writer_end. Suggested fix: guard the "else" part in that function with #ifndef MINIZ_NO_ARCHIVE_WRITING_APIS ... #endif.

**Comment by uroni** [comment]
This should work now
