### ISSUE TITLE
freopen_s is C11

### ISSUE THREAD

**Issue by gaborcsardi** [richgel999/miniz#64]
According to http://en.cppreference.com/w/c/io/freopen, `freopen_s` is C11, and it is only available on certain compilers, and if you request C11 using `__STDC_WANT_LIB_EXT1__`. On MinGW miniz generates a compiler warning for this currently.

Would you consider either
1) declaring the appropriate macros to request C11, and document that miniz requires C11, or
2) using `freopen` instead?

Thanks!

**Comment by uroni** [comment]
This is a special case for MSVC/mingw64

**Comment by gaborcsardi** [comment]
@uroni It is indeed, but still, `freopen_s` is only surely available if you test for `STDC_LIB_EXT1` and define `__STDC_WANT_LIB_EXT1__`.

So maybe you could do this on MSVC and MinGW64? 

And, since the current implementation does not work on older MinGW versions, maybe it would be better to fall back to freopen?

**Comment by SnapperTT** [comment]
I've just run into this issue (not compiling on Mingw64 due to freopen_s). It can be fixed by editing miniz_zip.c as follows:

Putting this here in case anyone else comes across this issue via the google machine

```
static FILE *mz_freopen(const char *pPath, const char *pMode, FILE *pStream)
{
    FILE *pFile = NULL;
    //if (freopen_s(&pFile, pPath, pMode, pStream))
     //   return NULL;

	pFile = freopen(pPath, pMode, pStream );
    return pFile;
}
```
