### ISSUE TITLE
example 2 broken

### ISSUE THREAD

**Issue by Klezstyle** [richgel999/miniz#71]
Hi,

Seems to be a typo in example2.c:

line 16:
#include "miniz_zip.h"

Should be:
#include "miniz.c"

or else does not compile in linux with gcc

**Comment by wdlkmpx** [comment]
shouldn't this be closed?
the change was applied by commit https://github.com/richgel999/miniz/commit/a3aeeb33070aca58b139e9c27f3a93cbe9b0af30
