### ISSUE TITLE
Build problems on OS X when _LARGEFILE64_SOURCE defined

### ISSUE THREAD

**Issue by tom-seddon** [richgel999/miniz#73]
I defined `_LARGEFILE64_SOURCE=1` on OS X, hoping to get rid of the `"Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files."` warning.

But the code then didn't build, because it ends up using the `defined(__GNUC__) && _LARGEFILE64_SOURCE` section. Then it tries to use `ftello64` (etc.), which OS X doesn't have.

Should `_LARGEFILE64_SOURCE` be tested on OS X anyway? It looks to be a glibc macro, and OS X doesn't use glibc. The OS X case should probably just be `#elif defined(__APPLE__)`, and never mind about `_LARGEFILE64_SOURCE`.

```
diff --git a/miniz_zip.c b/miniz_zip.c
index 18b6dbf..ad2fe4f 100644
--- a/miniz_zip.c
+++ b/miniz_zip.c
@@ -112,7 +112,7 @@ static FILE *mz_freopen(const char *pPath, const char *pMode, FILE *pStream)
 #define MZ_FFLUSH fflush
 #define MZ_FREOPEN(p, m, s) freopen64(p, m, s)
 #define MZ_DELETE_FILE remove
-#elif defined(__APPLE__) && _LARGEFILE64_SOURCE
+#elif defined(__APPLE__)
 #ifndef MINIZ_NO_TIME
 #include <utime.h>
 #endif
```

Thanks,

--Tom

**Comment by uroni** [comment]
Yes, I think it can be simply removed. There shouldn't be any (supported) apples around without large file support

**Comment by tom-seddon** [comment]
Thanks. PR will follow at some point.

--Tom
