### ISSUE TITLE
mz_zip_writer_add_mem() with MZ_DEFAULT_COMPRESSION always hits assert() 

### ISSUE THREAD

**Issue by JonnyH** [richgel999/miniz#81]
When calling mz_zip_writer_add_mem() with levels_and_flags set to MZ_DEFAULT_COMPRESSON (ie "-1") the assert

`MZ_ASSERT(bit_flags & MZ_ZIP_LDH_BIT_FLAG_HAS_LOCATOR); `

in mz_zip_writer_add_mem_ex_v2() (miniz_zip.c line 3360) always fails with a non-zero buf_size.

This appears to be because the flags are set to -1, so all bits are set. This causes the test:

`if (uncomp_size || (buf_size && !(level_and_flags & MZ_ZIP_FLAG_COMPRESSED_DATA)))`

to fail, as (level_and_flags & MZ_ZIP_FLAG_COMPRESSED_DATA) is true. This means the following line is never executed:

`bit_flags |= MZ_ZIP_LDH_BIT_FLAG_HAS_LOCATOR;`

Then, the following code is run:
`if ((int)level_and_flags < 0)
    level_and_flags = MZ_DEFAULT_LEVEL;`

This appears to be trying to catch the MZ_DEFAULT_COMPRESSION case. Should this check have been done before the MZ_ZIP_FLAG_COMPRESSED_DATA check? As otherwise this then falls through to `if (uncomp_size)` on line 3355, and then the assert mentioned above.

Note - this can be repro'd in miniz_tester.cpp, mode "a" with the "-a" option, if you modify one of the mz_zip_writer_add_file() calls to use MZ_DEFAULT_COMPRESSON

Note 2 - the line numbers etc. are based on revision 0f6b199

**Comment by uroni** [comment]
Pulled your fix with https://github.com/richgel999/miniz/commit/9c88e826a251db9be4611a570e73995ecde66914
