### ISSUE TITLE
Corrupt archive if uncompressed file smaller than 4B

### ISSUE THREAD

**Issue by espakm** [richgel999/miniz#92]
I am trying to create an archive that contains a file of size 1B, along with other regular files. The zip file is created, but I cannot extract it with other tools. I found that miniz does not compress files smaller than 4B. This would not be a problem itself, but it records the compression method as "DEFLATE" (8) instead of "STORE" (0) in the central dir.

If I change the 8 to 0 by a hexa editor, I can extract the zip archive.

**Comment by espakm** [comment]
PR sent:
https://github.com/richgel999/miniz/pull/93

**Comment by uroni** [comment]
Thanks for reporting! 46cdde2ac5ea1fbc9cdd8a5c8adaff8911f11b4c should fix this. I have moved the check up as it was in the 1.x version.

**Comment by espakm** [comment]
That's also good, thanks.
I see a mistake with the indentation, the lines 3315-3321 have slipped inwards by 3 spaces.
