### ISSUE TITLE
Where's the Documentation?

### ISSUE THREAD

**Issue by sukhchainn** [richgel999/miniz#97]
There is no documentation on how to use this library and examples are not clear enough,
Needs better commenting.

**Comment by kennyrkun** [comment]
I [wrapped some of it](https://github.com/kennyrkun/kunlib/tree/master/C%2B%2B/Zip), it might be easier to understand in those files. I only added what I needed, but it works.

**Comment by Mr-zhangyh** [comment]
Such a simple library shouldn't be so messy. Please refer to the library of kuba, which is simple and straightforward. Zeux's Pugixml library is an example of open source! There is both simple source code and complete tutorials.
[kuba-- / zip](https://github.com/kuba--/zip)
[zeux / pugixml](https://github.com/zeux/pugixml)
