### ISSUE TITLE
Please don't use assert()

### ISSUE THREAD

**Issue by Photosounder** [richgel999/miniz#99]
My Xcode doesn't seem to like it (it says `Undefined symbols for architecture x86_64: "_assert"`), and then I don't like the idea of miniz just `abort()`ing my whole program without even telling me anything because `stderr` is usually not logged, and generally it's just bad practice, see https://www.softwariness.com/articles/assertions-in-cpp/

At least we should be able to define our own replacement, but if I'm not mistaken the line `#define MZ_ASSERT(x) assert(x)` not being preceded by a `#ifndef MZ_ASSERT` means that I can't define it right before including `miniz.h`. For now I guess I'll just use `#define assert(ignore) ((void)0)`, but depending on how the `assert()` is used that might be risky (although it doesn't seem like it should be a problem here.

**Comment by uroni** [comment]
Please disable asserts by compiling with NDEBUG defined. This is what everyone does.
